apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-secret
  namespace: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager 
    kind: ClusterSecretStore
  target:
    name: argocd-github-secret
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
  - secretKey: clientSecret
    remoteRef:
      key: dev/argocd/github-oauth
      property: clientSecret