apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: inventory-service-dev

resources:
- ../../base
- network-policy.yaml
images:
- name: inventory-service
  newName: 438950223046.dkr.ecr.eu-central-1.amazonaws.com/myapp/inventory-service
  newTag: 51da120
