controller:
  type: daemonset

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi

alloy:
  extraConfig: |
    otelcol.receiver.otlp "default" {
      grpc { endpoint = "0.0.0.0:4317" }
      http { endpoint = "0.0.0.0:4318" }
      output { traces = [otelcol.exporter.otlp.tempo.input] }
    }
    otelcol.exporter.otlp "tempo" {
      client { endpoint = "dev-infra-tempo:4317" }
    }