apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storefront-bff-dev

resources:
- ../../base
- network-policy.yaml
images:
- name: storefront-bff
  newName: 438950223046.dkr.ecr.eu-central-1.amazonaws.com/myapp/storefront-bff
  newTag: 6eeff02
